/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Direction_1_aliases.h"
#include "Direction_1.h"
#include "Control_Reg_6.h"
#include "PWM_out_1_aliases.h"
#include "PWM_out_1.h"
#include "Heartbeat_aliases.h"
#include "Heartbeat.h"
#include "Control_Reg_1.h"
#include "Control_Reg_5.h"
#include "Direction_2_aliases.h"
#include "Direction_2.h"
#include "PWM_out_2_aliases.h"
#include "PWM_out_2.h"
#include "Control_Reg_2.h"
#include "Sleep2_aliases.h"
#include "Sleep2.h"
#include "Pin_1_aliases.h"
#include "Pin_1.h"
#include "UART.h"
#include "Control_Reg_3.h"
#include "isr_rx.h"
#include "Sleep1_aliases.h"
#include "Sleep1.h"
#include "Control_Reg_4.h"
#include "PWM_1.h"
#include "Clock_1.h"
#include "PWM_2.h"
#include "Timer_1.h"
#include "pulse_ready_isr.h"
#include "pos_reset.h"
#include "UART_IntClock.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

